packages/app-lixi/src/components/Lixi/index.tsx

Fix crash issue when no lixi selected

Fix Lixi Crash

---

packages/app-lixi/src/components/Lixi/CreateLixiForm.tsx

fix error when yarn build

---

packages/lixi-components/src/components/Common/EnhancedInputs.tsx
packages/lixi-components/src/components/Common/ScanQRCode.tsx

fix issue camera

---

packages/app-lixi/src/components/Home/Home.tsx
packages/app-lixi/src/components/Wallet/FullWallet.tsx
packages/app-lixi/src/components/Wallet/WalletInfo.tsx
packages/app-lixi/src/containers/Sidebar/SidebarContent.tsx
packages/app-lixi/src/pages/wallet.tsx

create new component wallet info for lixi

create new component wallet info for lixi

---

packages/app-lixi/src/store/account/saga.ts

Fix Refresh button call duplicate API issue

Fix Refresh button call duplicate API issue

---

packages/app-lixi-api/prisma/migrations/20220707151651_upload_fixed/migration.sql
packages/app-lixi-api/prisma/schema.prisma
packages/app-lixi-api/src/modules/core/lixi/lixi.service.ts
packages/app-lixi-api/src/modules/core/lixi/processors/create-sub-lixies.isolated.processor.ts
packages/app-lixi/src/store/lixi/saga.ts
packages/lixi-models/src/lib/lixi.ts

Reverts bcProFoundation/lixilotus#60

Revert "fix cannot create lixi"

---

packages/app-lixi-api/src/app.module.ts
packages/app-lixi-api/src/modules/core/core.module.ts
packages/app-lixi-api/src/modules/page/page.controller.ts
packages/app-lixi-api/src/modules/page/page.module.ts
packages/app-lixi/src/components/Home/Home.tsx
packages/app-lixi/src/components/Pages/CreatePageComponent.tsx
packages/app-lixi/src/pages/page/[slug].tsx
packages/app-lixi/src/pages/page/create.tsx
packages/app-lixi/src/store/page/action.ts
packages/app-lixi/src/store/page/api.ts
packages/app-lixi/src/store/page/pageDetail.model.ts
packages/app-lixi/src/store/page/reducer.ts
packages/app-lixi/src/store/page/saga.ts
packages/app-lixi/src/store/page/selectors.ts
packages/app-lixi/src/store/page/state.ts
packages/app-lixi/src/store/rootSaga.ts

implement create page

---

packages/app-lixi-api/prisma/migrations/20220721075102_/migration.sql
packages/app-lixi-api/prisma/schema.prisma
packages/app-lixi-api/src/modules/core/claim/claim.controller.ts
packages/app-lixi-api/src/modules/page/page.controller.ts
packages/app-lixi/src/components/Pages/CreatePageComponent.tsx
packages/app-lixi/src/lang/locales/en_US.ts
packages/app-lixi/src/lang/locales/vi_VN.ts
packages/app-lixi/src/store/page/action.ts
packages/app-lixi/src/store/page/saga.ts
packages/lixi-models/src/lib/claim.ts
packages/lixi-models/src/lib/page/create-page.command.ts
packages/lixi-models/src/lib/page/page.dto.ts
packages/lixi-models/src/lib/page/page.model.ts

fix flow create page + handle claim voucher abcpay

---

packages/app-lixi-api/src/modules/core/claim/claim.controller.ts

bypass captcha Abcpay

---

packages/app-lixi-api/src/modules/core/claim/claim.controller.ts

comment out code claim

---

packages/app-lixi-api/src/modules/page/page.controller.ts
packages/app-lixi/src/components/Pages/PagesListing.tsx
packages/app-lixi/src/store/page/action.ts
packages/app-lixi/src/store/page/api.ts
packages/app-lixi/src/store/page/reducer.ts
packages/app-lixi/src/store/page/saga.ts
packages/app-lixi/src/store/page/selectors.ts

fetch pages to show in home page

---

packages/app-lixi-api/src/modules/page/page.controller.ts
packages/app-lixi/src/components/Pages/PageDetail.tsx
packages/app-lixi/src/components/Pages/PagesListing.tsx
packages/app-lixi/src/pages/page/[slug].tsx
packages/app-lixi/src/store/page/api.ts

implement page detail

---

packages/app-lixi/src/@types/styled.d.ts
packages/app-lixi/src/components/Common/EnvelopeCarousel.tsx
packages/app-lixi/src/components/Home/Home.tsx
packages/app-lixi/src/components/Layout/MainLayout/theme.ts
packages/app-lixi/src/components/Pages/PagesListing.tsx
packages/app-lixi/src/components/Settings/index.tsx
packages/app-lixi/src/containers/Topbar/index.tsx
packages/app-lixi/src/styles/style.less
packages/app-lixi/src/styles/variables.less
packages/lixi-components/src/components/NavButton/NavButton.tsx

define variable global

---

packages/app-lixi/src/components/Pages/PageDetail.tsx
packages/app-lixi/src/lang/locales/en_US.ts
packages/app-lixi/src/lang/locales/vi_VN.ts
packages/app-lixi/src/store/lixi/actions.ts

**<h2>[Able to share store (page) in the social media · Issue #3 · bcProFoundation/lixilotus](https://github.com/bcProFoundation/lixilotus/issues/3)</h2>**
<h2>Result</h2>

Update share page to Social Media for PageDetail

---

packages/app-lixi/src/components/Layout/MainLayout/index.tsx
packages/app-lixi/src/components/Pages/PagesListing.tsx
packages/app-lixi/src/components/Wallet/FullWallet.tsx
packages/app-lixi/src/containers/Sidebar/SideBarRanking.tsx
packages/app-lixi/src/containers/Sidebar/SideBarShortcut.tsx
packages/app-lixi/src/containers/Topbar/index.tsx
packages/lixi-components/src/components/Footer/Footer.tsx

implement sticky header + sidebar

---

packages/app-lixi/src/components/Layout/MainLayout/index.tsx
packages/app-lixi/src/components/Pages/PagesListing.tsx
packages/app-lixi/src/containers/Sidebar/SideBarShortcut.tsx
packages/app-lixi/src/containers/Sidebar/SidebarContent.tsx
packages/lixi-models/src/constants/index.ts
packages/lixi-models/src/constants/navBarHeaderList.ts

polish home page & implement navbar header

---

packages/app-lixi-api/src/modules/core/claim/claim.controller.ts
packages/app-lixi/src/components/Lixi/CreateLixiConfirmationModal.tsx
packages/app-lixi/src/components/Lixi/LixiList.tsx
packages/app-lixi/src/components/Lixi/index.tsx
packages/lixi-models/src/constants/navBarHeaderList.ts

- Revert index.tsx (lixi) for details of lixi
- Moved UI to LixiList.tsx

revert index lixi

---

packages/app-lixi/src/components/Common/CreatePostCard.tsx
packages/app-lixi/src/components/Lixi/index.tsx
packages/app-lixi/src/components/Pages/PageListItem.tsx
packages/app-lixi/src/styles/style.less
packages/app-lixi/src/styles/themes/light.less

polish ui & handle editor create post

---

packages/app-lixi/src/components/Common/PrimaryButton.tsx
packages/app-lixi/src/components/Common/Uploader.tsx
packages/app-lixi/src/components/Lixi/CreateLixiFormModal.tsx
packages/app-lixi/src/components/Lixi/LixiList.tsx
packages/app-lixi/src/styles/style.less
packages/app-lixi/src/styles/variables.less

customine btn for app

---

packages/app-lixi/src/components/Layout/MainLayout/index.tsx
packages/app-lixi/src/components/Lixi/LixiList.tsx
packages/app-lixi/src/components/Lixi/LixiListItem.tsx
packages/app-lixi/src/containers/Sidebar/SideBarRanking.tsx
packages/app-lixi/src/containers/Sidebar/SideBarShortcut.tsx
packages/app-lixi/src/styles/style.less
packages/app-lixi/src/styles/variables.less

lixi management desktop view & modal default

---

packages/app-lixi/src/components/Pages/PageHomeFeed.tsx
packages/app-lixi/src/containers/Sidebar/SideBarRanking.tsx
packages/app-lixi/src/styles/style.less

implement manage accounts & polish ui

---

packages/app-lixi-api/src/modules/page/post.resolver.ts
packages/app-lixi/src/containers/Sidebar/SideBarShortcut.tsx
packages/app-lixi/src/containers/Sidebar/SidebarContent.tsx
packages/app-lixi/src/store/rootSaga.ts

Integrate create post with the editor #234

Integrate create post with the editor #234

---

packages/app-lixi-api/src/modules/core/claim/claim.controller.ts
packages/app-lixi/src/components/Claim/LixiClaimed.tsx
packages/app-lixi/src/components/Layout/ClaimedLayout/index.tsx
packages/app-lixi/src/components/Layout/PageDetailLayout/index.tsx
packages/app-lixi/src/lang/locales/en_US.ts
packages/app-lixi/src/lang/locales/vi_VN.ts
packages/app-lixi/src/pages/claimed/[slug].tsx
packages/lixi-components/src/components/Common/BalanceHeader.tsx
packages/lixi-models/src/constants/navBarHeaderList.ts
packages/lixi-models/src/lib/claim.ts

implement claimed result page

---

packages/app-lixi/src/components/Common/InfoCardUser.tsx
packages/app-lixi/src/components/Layout/ClaimedLayout/index.tsx
packages/app-lixi/src/components/Layout/MainLayout/index.tsx
packages/app-lixi/src/components/Layout/PageDetailLayout/index.tsx
packages/app-lixi/src/components/Lixi/LixiList.tsx
packages/app-lixi/src/components/Pages/PageHomeFeed.tsx
packages/app-lixi/src/components/Pages/PageListItem.tsx
packages/app-lixi/src/components/Posts/PostListItem.tsx
packages/app-lixi/src/components/Wallet/FullWallet.tsx
packages/app-lixi/src/components/Wallet/WalletInfo.tsx
packages/app-lixi/src/containers/Sidebar/SideBarRanking.tsx
packages/app-lixi/src/containers/Sidebar/SideBarShortcut.tsx
packages/app-lixi/src/containers/Sidebar/SidebarContent.tsx
packages/app-lixi/src/styles/style.less
packages/app-lixi/src/styles/variables.less

polish ui app

---

packages/app-lixi/src/components/Common/CreatePostCard.tsx
packages/app-lixi/src/styles/style.less

block upload image base 64 in editor

---

packages/app-lixi/src/components/Common/navBarHeaderList.ts
packages/app-lixi/src/components/Layout/ClaimedLayout/index.tsx
packages/app-lixi/src/components/Layout/MainLayout/index.tsx
packages/app-lixi/src/components/Layout/PageDetailLayout/index.tsx
packages/app-lixi/src/containers/Sidebar/SideBarRanking.tsx
packages/app-lixi/src/store/lixi/actions.ts

fixed issue about asynchronous intl

---

packages/app-lixi/package.json
packages/app-lixi/src/components/Common/InfoCardUser.tsx
packages/app-lixi/src/components/Posts/PostListItem.tsx

fix show content post in home page

---

packages/app-lixi/package.json
packages/app-lixi/src/components/Common/CreatePostCard.tsx
packages/app-lixi/src/components/Common/Plate/BasicElementToolbarButtons.tsx
packages/app-lixi/src/components/Common/Plate/BasicMarkToolbarButtons.tsx
packages/app-lixi/src/components/Common/Plate/EmojiToolbarButtons.tsx
packages/app-lixi/src/components/Common/Plate/Plugin/exitBreakPlugin.ts
packages/app-lixi/src/components/Common/Plate/Plugin/imagePlugins.ts
packages/app-lixi/src/components/Common/Plate/Plugin/linkPlugin.tsx
packages/app-lixi/src/components/Common/Plate/Plugin/resetBlockTypePlugin.ts
packages/app-lixi/src/components/Common/Plate/Plugin/softBreakPlugin.ts
packages/app-lixi/src/components/Common/Uploader.tsx
packages/app-lixi/src/styles/style.less
yarn.lock

improve editor

---

packages/app-lixi/src/components/Common/CreatePostCard.tsx
packages/app-lixi/src/components/Common/SearchBox.tsx
packages/app-lixi/src/components/Layout/ClaimedLayout/index.tsx
packages/app-lixi/src/components/Layout/EmptyLayout/index.tsx
packages/app-lixi/src/components/Layout/MainLayout/index.tsx
packages/app-lixi/src/components/Layout/PageDetailLayout/index.tsx
packages/app-lixi/src/components/Layout/PostDetailLayout/index.tsx
packages/app-lixi/src/components/Pages/PageListItem.tsx
packages/app-lixi/src/components/Posts/PostListItem.tsx
packages/app-lixi/src/components/Posts/PostsListing.tsx
packages/app-lixi/src/containers/Sidebar/SideBarShortcut.tsx
packages/app-lixi/src/pages/_app.tsx
packages/app-lixi/src/pages/post/[slug].tsx

polish scroll in app

---

packages/app-lixi/src/components/Tokens/TokensListing.tsx

Default sort token list by burn

---

packages/app-lixi/src/components/Common/CreatePostCard.tsx
packages/app-lixi/src/components/Common/Embed/Embed.tsx
packages/app-lixi/src/components/Common/Embed/Facebook/FacebookEmbed.tsx
packages/app-lixi/src/components/Common/Embed/Reddit/RedditEmbed.tsx
packages/app-lixi/src/components/Common/Embed/Twitter/TweetEmbed.tsx
packages/app-lixi/src/components/Posts/PostListItem.tsx
packages/app-lixi/src/components/Posts/PostsListing.tsx
packages/app-lixi/src/pages/_app.tsx

import post from social

---

packages/app-lixi/src/containers/Sidebar/SideBarShortcut.tsx
packages/app-lixi/src/styles/style.less

fix issue ui notification

---

packages/app-lixi/src/components/Layout/MainLayout/index.tsx
packages/app-lixi/src/components/Layout/PageDetailLayout/index.tsx
packages/app-lixi/src/components/Posts/PostDetail.tsx
packages/app-lixi/src/containers/Sidebar/SideBarRanking.tsx
packages/app-lixi/src/pages/_document.tsx
packages/lixi-components/src/components/Footer/Footer.tsx

polish ui mobile view

---

packages/app-lixi/src/components/Layout/ClaimedLayout/index.tsx
packages/app-lixi/src/components/Layout/EmptyLayout/index.tsx
packages/app-lixi/src/components/Layout/PageDetailLayout/index.tsx
packages/app-lixi/src/components/Layout/PostDetailLayout/index.tsx
packages/app-lixi/src/components/Settings/index.tsx

fix break ui layout

---

packages/app-lixi/src/components/Common/Lexical/EditorLexical.tsx
packages/app-lixi/src/components/Common/Lexical/plugins/FloatingLinkEditorPlugin/index.tsx

add image editor & change behavior insert link

---

packages/app-lixi/src/styles/variables.less

hot fix app

---

packages/app-lixi/src/components/Common/Comment.tsx
packages/app-lixi/src/components/Common/Counter.tsx
packages/app-lixi/src/components/Common/CreatePostCard.tsx
packages/app-lixi/src/components/Layout/MainLayout/index.tsx
packages/app-lixi/src/components/Posts/CommentListItem.tsx
packages/app-lixi/src/components/Posts/PostDetail.tsx
packages/app-lixi/src/containers/Sidebar/SideBarShortcut.tsx
packages/app-lixi/src/containers/Sidebar/SidebarContent.tsx
packages/app-lixi/src/containers/Topbar/index.tsx

polish ui post & comment

---

packages/app-lixi/src/components/Common/InfoCardUser.tsx
packages/app-lixi/src/components/Common/Lexical/EditorLexical.tsx
packages/app-lixi/src/components/Pages/PageListItem.tsx
packages/app-lixi/src/components/Posts/PostListItem.tsx
packages/app-lixi/src/components/Settings/index.tsx
packages/app-lixi/src/containers/Sidebar/SidebarContent.tsx

Ericson polish UI 16012023

---

packages/app-lixi/src/components/Common/Lexical/EditorLexical.tsx
packages/app-lixi/src/components/Pages/PageListItem.tsx
packages/app-lixi/src/components/Posts/PostDetail.tsx
packages/app-lixi/src/components/Posts/PostListItem.tsx

change config url image

---

packages/app-lixi/src/components/Layout/ClaimedLayout/index.tsx
packages/app-lixi/src/components/Layout/EmptyLayout/index.tsx
packages/app-lixi/src/components/Layout/MainLayout/index.tsx
packages/app-lixi/src/components/Layout/PageDetailLayout/index.tsx
packages/app-lixi/src/components/Pages/PageHomeFeed.tsx
packages/app-lixi/src/components/Posts/PostsListing.tsx
packages/app-lixi/src/components/Settings/index.tsx
packages/app-lixi/src/components/Wallet/FullWallet.tsx
packages/app-lixi/src/containers/Sidebar/DummySidebar.tsx
packages/app-lixi/src/styles/style.less

polish layout

---

packages/app-lixi/src/components/Common/CreatePostCard.tsx
packages/app-lixi/src/components/Common/ModalManager.tsx
packages/app-lixi/src/components/Posts/PostDetail.tsx
packages/app-lixi/src/pages/_app.tsx
packages/app-lixi/src/styles/style.less
packages/app-lixi/src/styles/themes/lightTheme.ts

apply new customize theme v5 & polish ui

---

packages/app-lixi/src/components/Token/TokensFeed.tsx
packages/app-lixi/src/components/Token/TokensListing.tsx

fix build UI

---

packages/app-lixi/src/components/Pages/PageListItem.tsx
packages/app-lixi/src/components/Posts/PostDetail.tsx
packages/app-lixi/src/components/Posts/PostListItem.tsx

polish new layout & image

---

packages/app-lixi/src/containers/Sidebar/SideBarShortcut.tsx

Nhan fix issue 496

---

packages/app-lixi-api/src/modules/core/upload/upload.controller.ts
packages/app-lixi/src/containers/Sidebar/SideBarShortcut.tsx
packages/lixi-prisma/prisma/schema.prisma

Complete back-end resize thumbnail image width: 800px, 320px and 40px.

Nhan fix issue 494

---

packages/app-lixi/src/components/Common/Ticker.ts

Expectation:
Change icon Lotus succesfully!

change url icon

---

packages/app-lixi/src/components/Wallet/FullWallet.tsx

Added icon Encryption and fix css

Fix issue-482

---

packages/app-lixi/src/components/Token/TokensFeed.tsx
packages/app-lixi/src/lang/locales/en_US.ts
packages/app-lixi/src/lang/locales/vi_VN.ts

Fix issue #514

---

packages/app-lixi/src/components/Posts/PostListItem.tsx

Hello, i fixed code img. Please check at "https://dev.lixilotus.com//" again. Tell me if it is not still work. Thank you

Fix img dev lixilotus

---

packages/app-lixi/src/styles/style.less

fix issue#519 - Create Page

---

packages/app-lixi/src/components/NotificationPopup/index.tsx

Notification UI Code

---

packages/app-lixi/src/components/Lixi/CreateLixiFormModal.tsx
packages/app-lixi/src/components/Lixi/LixiList.tsx
packages/app-lixi/src/components/Lixi/index.tsx

I have fixed issue 536, please check again. Thank you so much.

fix rouned number, error date

---

packages/app-lixi/src/components/Posts/PostDetail.tsx

fix-min-height

---

packages/app-lixi/src/components/NotificationPopup/index.tsx
packages/app-lixi/src/store/settings/saga.ts
packages/lixi-components/src/components/Footer/Footer.tsx

Relative time issue 554

---

packages/app-lixi/src/components/NotificationPopup/index.tsx
packages/app-lixi/src/components/Posts/PostListItem.tsx
packages/app-lixi/src/store/settings/saga.ts
packages/app-lixi/src/utils/formatting.ts

fix-ago-format

---

packages/app-lixi/src/components/Posts/PostDetail.tsx

add log to debug comment

---

packages/app-lixi/src/containers/Sidebar/SideBarRanking.tsx
packages/app-lixi/src/lang/locales/en_US.ts
packages/app-lixi/src/lang/locales/vi_VN.ts

fix-issue-597

---

packages/app-lixi/src/containers/Sidebar/SideBarShortcut.tsx

Fix sidebar color

---

packages/app-lixi/src/components/Posts/PostDetail.tsx

Reverts bcProFoundation/lixilotus#632

Revert "Issue:623"

---

packages/app-lixi/src/components/Common/ShareSocialButton.tsx
packages/app-lixi/src/components/Posts/PostDetail.tsx
packages/app-lixi/src/components/Posts/PostListItem.tsx

Fix issue #630

---

packages/app-lixi/src/pages/post/[slug].tsx
packages/app-lotus-temple/src/pages/_app.tsx

issue #664

---

packages/app-lixi/src/components/Common/BurnModal.tsx
packages/app-lixi/src/components/Posts/PostDetail.tsx
packages/app-lixi/src/components/Posts/PostListItem.tsx
packages/app-lixi/src/lang/locales/en_US.ts
packages/app-lixi/src/lang/locales/vi_VN.ts

issue 667: add fee for account or post

Add fee for account or page

---

packages/app-lixi/src/containers/Sidebar/SideBarRanking.tsx

separate top-page and top-account

fix issue-673

---

packages/app-lixi/src/components/Common/ShareSocialButton.tsx
packages/lixi-components/src/components/Footer/Footer.tsx

delete text icon in footer and share

delete text in mobile-view

---

packages/app-lixi/src/components/Pages/PageDetail.tsx
packages/app-lixi/src/components/Profile/ProfileDetail.tsx

[Issue-716: Follow button on pages are not showing in mobile](https://github.com/bcProFoundation/lixilotus/issues/716)
[Issue-718: Edit profile and edit cover photo options not available for page in mobile](https://github.com/bcProFoundation/lixilotus/issues/718)

Issue-716 and Issue-718

---

packages/app-lixi/src/lang/locales/en_US.ts
packages/app-lixi/src/lang/locales/vi_VN.ts
packages/lixi-prisma/prisma/seeds/categories.ts

edit category natural -> nature
add 4 new category :
Agriculture 
Humanitarian
Permaculture
Real Estate

issue-762: add and edit category

---

packages/app-lixi/src/components/Pages/CreatePageModal.tsx

issue-774: fix case-sensitive at category when create page

---

packages/app-lixi/src/components/Common/BurnModal.tsx
packages/app-lixi/src/lang/locales/en_US.ts
packages/app-lixi/src/lang/locales/vi_VN.ts

issue-667: add text "Miner's fees excluded"

---

packages/app-lixi/src/components/Common/BurnModal.tsx
packages/app-lixi/src/styles/style.less

remove some space between line

---

packages/app-lixi/src/lang/locales/vi_VN.ts

"Xếp hạng tài khoản đã đốt" => "Xếp hạng tài khoản"

issue-789: remove text in vietnamese

---

packages/app-lixi/src/components/Common/Lexical/EditorLexical.tsx
packages/app-lixi/src/components/Common/Lexical/plugins/TwitterPlugin/index.tsx

issue-768: edit size of icon twitter

---

packages/app-lixi/src/components/Common/FilterBurn.tsx
packages/app-lixi/src/lang/locales/vi_VN.ts

Limit level under 1000 and edit text "Nhà" => "Trang chủ"

Issue 771 and edit text home

---

packages/app-lixi/src/lang/locales/vi_VN.ts

edit text miner' fee

---

packages/app-lixi/src/components/Profile/ProfileDetail.tsx

issue-663: edit fixed layout of profile

---

packages/app-lixi/src/pages/_document.tsx
packages/app-lixi/src/styles/style.less
packages/lixi-components/src/components/Footer/Footer.tsx

polish ui experience user use in browser

---

packages/app-lixi-api/schema.graphql
packages/app-lixi/package.json
packages/app-lixi/src/components/Common/CreatePostCard.tsx
packages/app-lixi/src/components/Common/Lexical/EditorLexical.tsx
packages/app-lixi/src/components/Common/Lexical/plugins/MyCustomAutoFocusPlugin.tsx
packages/app-lixi/src/components/Hashtag/index.tsx
packages/app-lixi/src/components/Pages/PageDetail.tsx
packages/app-lixi/src/components/Posts/PostContent.tsx
packages/app-lixi/src/components/Posts/PostListItem.tsx
packages/app-lixi/src/components/Posts/PostsListing.tsx
packages/app-lixi/src/components/Token/TokensFeed.tsx
yarn.lock

clickable hashtag #806, post to a hashtag #807

---

packages/app-lixi-api/src/modules/core/upload/upload.controller.ts
packages/app-lixi/src/components/Posts/PostDetail.tsx

handle issue 692 693

---

packages/app-lixi/src/components/Layout/PageDetailLayout/index.tsx
packages/app-lixi/src/components/Lixi/LixiList.tsx

task-737: responsive token list
task-758: display text reset

issue-737-758

---

packages/app-lixi/src/components/Profile/ProfileDetail.tsx

issue-681: add skeleton 

---

packages/app-lixi/src/components/Common/Lexical/plugins/MyCustomAutoFocusPlugin.tsx

handle issue 847

---

packages/app-lixi/public/manifest.json
packages/app-lixi/src/components/Posts/PostListItem.tsx

handle image rotate not correct

---

packages/app-lixi/src/components/Common/Lexical/plugins/TwitterPlugin/index.tsx

Trimming url to valid url
https://twitter.com/<page>/status/<status_id>/photo/1 ->https://twitter.com/<page>/status/<status_id>
https://twitter.com/<page>/status/<status_id>/?param=abc => https://twitter.com/<page>/status/<status_id>

Fix issue 821

---

packages/app-lixi/src/lang/locales/en_US.ts
packages/app-lixi/src/lang/locales/vi_VN.ts
packages/app-lixi/src/pages/_app.tsx
packages/app-lixi/src/pages/page/[slug].tsx
packages/app-lixi/src/pages/post/[slug].tsx
packages/app-lixi/src/pages/profile/[slug].tsx

issue-866: change title
